name: flutter_participants_lottery
description: Osallistujien arvontasovellus. A participants lottery app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

_author: Arttu Ylhävuori

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  circular_countdown_timer: ^0.2.3
  emoji_alert: ^1.1.0
  google_fonts: ^4.0.4
  random_avatar: ^0.0.8
  get: ^4.6.5
  get_storage: ^2.1.1
  about: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  pubspec_extract: ^2.0.5
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - LICENSE.md
    - README.md
