name: flutter_participants_lottery
description: A participants lottery app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  circular_countdown_timer: ^0.2.1
  shared_preferences: ^2.0.15
  emoji_alert:  ^1.1.0
  # audioplayers: ^0.19.1 # Do not use for now (to support also Windows desktop)
  envify: any
  google_fonts: ^3.0.1
  get: ^4.6.5

dev_dependencies:
  envify_generator: any
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - LICENSE.md
    - README.md
    - assets/images/lumihiutale.png
    - assets/images/kukkia_ruohikolla.png

  # Do not use for now (to support also Windows desktop)
  # assets:
  #   - assets/aika_loppui.mp3
  #   - assets/arvonta_kaynnissa.mp3
