name: flutter_participants_lottery
description: Osallistujien arvontasovellus. A participants lottery app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.0+1

_author: Arttu Ylhävuori
repository: https://github.com/areee/flutter_participants_lottery

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  about: ^2.1.3
  circular_countdown_timer: ^0.2.4
  emoji_alert: ^1.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  random_avatar: ^0.0.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^5.0.0
  pubspec_extract: ^2.0.5

flutter:
  uses-material-design: true
  assets:
    - LICENSE.md
