name: flutter_participants_lottery
description: Osallistujien arvontasovellus. A participants lottery app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.2.0+1

_author: Arttu Ylhävuori

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  about: ^2.1.3
  circular_countdown_timer: ^0.2.3
  emoji_alert: ^1.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  random_avatar: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  pubspec_extract: ^2.0.5

flutter:
  uses-material-design: true
  assets:
    - LICENSE.md
    - README.md
