name: Deploy Flutter web app to Github Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart run pubspec_extract
      - run: flutter build web --release --base-href "/flutter_participants_lottery/"